services:
  finality-explorer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_FINALITY_GADGET_API_URL=${NEXT_PUBLIC_FINALITY_GADGET_API_URL}
    image: snapchain/finality-explorer:latest
    ports:
      - "13000:3000"
    environment:
      - NEXT_PUBLIC_FINALITY_GADGET_API_URL=${NEXT_PUBLIC_FINALITY_GADGET_API_URL}
    env_file:
      - .env
    restart: unless-stopped
