name: ci

on:
  pull_request:
    branches:
      - "**"

jobs:
  build_lint_format:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run format
        run: npm run format

      - name: Run build
        run: npm run build
